#include "MpvWidget.h"
#include "util/Utils.h"
#include <QOpenGLContext>
#include <QOpenGLFunctions>
#include <QMetaObject>
#include <QByteArray>
#include <cmath>
#include <mpv/client.h>
#include <mpv/render.h>
#include <mpv/render_gl.h>

MpvWidget::MpvWidget(QWidget*p):QOpenGLWidget(p){forceCLocaleForMpv();setMinimumSize(640,360);setFocusPolicy(Qt::StrongFocus); mpv=mpv_create(); if(!mpv)qFatal("no mpv"); check_mpv_error(mpv_set_option_string(mpv,"terminal","yes")); check_mpv_error(mpv_set_option_string(mpv,"msg-level","all=warn,libmpv_render=fatal")); check_mpv_error(mpv_set_option_string(mpv,"hwdec","auto-safe")); check_mpv_error(mpv_set_option_string(mpv,"video-unscaled","downscale-big")); check_mpv_error(mpv_set_option_string(mpv,"vo","libmpv")); check_mpv_error(mpv_set_option_string(mpv,"input-default-bindings","no")); check_mpv_error(mpv_set_option_string(mpv,"osc","no")); check_mpv_error(mpv_initialize(mpv)); mpv_observe_property(mpv,1,"time-pos",MPV_FORMAT_DOUBLE); mpv_observe_property(mpv,2,"duration",MPV_FORMAT_DOUBLE); mpv_observe_property(mpv,3,"pause",MPV_FORMAT_FLAG); mpv_observe_property(mpv,4,"path",MPV_FORMAT_STRING); mpv_observe_property(mpv,5,"volume",MPV_FORMAT_DOUBLE); mpv_observe_property(mpv,6,"mute",MPV_FORMAT_FLAG); mpv_set_wakeup_callback(mpv,wakeup,this);} 
MpvWidget::~MpvWidget(){makeCurrent(); if(ctx)mpv_render_context_free(ctx); doneCurrent(); if(mpv)mpv_terminate_destroy(mpv);} 
void MpvWidget::loadFile(const QString&p){cur=p; QByteArray b=p.toUtf8(); const char*cmd[]={"loadfile",b.constData(),"replace",nullptr}; check_mpv_error(mpv_command_async(mpv,0,cmd));} void MpvWidget::stopPlayback(){cur.clear(); const char*cmd[]={"stop",nullptr}; check_mpv_error(mpv_command_async(mpv,0,cmd)); update();} QString MpvWidget::currentFilePath()const{return cur;} void MpvWidget::togglePause(){const char*cmd[]={"cycle","pause",nullptr};check_mpv_error(mpv_command_async(mpv,0,cmd));} void MpvWidget::toggleMute(){const char*cmd[]={"cycle","mute",nullptr};check_mpv_error(mpv_command_async(mpv,0,cmd));} void MpvWidget::changeVolume(double d){QByteArray v=QByteArray::number(d,'f',1); const char*cmd[]={"add","volume",v.constData(),nullptr};check_mpv_error(mpv_command_async(mpv,0,cmd));} void MpvWidget::setVolume(double v){QByteArray b=QByteArray::number(qBound(0.0,v,130.0),'f',1); const char*cmd[]={"set","volume",b.constData(),nullptr};check_mpv_error(mpv_command_async(mpv,0,cmd));} void MpvWidget::setMute(bool m){const char*cmd[]={"set","mute",m?"yes":"no",nullptr};check_mpv_error(mpv_command_async(mpv,0,cmd));} void MpvWidget::seekAbsolute(double s){QByteArray b=QByteArray::number(s,'f',3); const char*cmd[]={"seek",b.constData(),"absolute","exact",nullptr};check_mpv_error(mpv_command_async(mpv,0,cmd));} void MpvWidget::seekRelative(double s){QByteArray b=QByteArray::number(s,'f',3); const char*cmd[]={"seek",b.constData(),"relative","exact",nullptr};check_mpv_error(mpv_command_async(mpv,0,cmd));}
void MpvWidget::setMaxVideoScale(double scale){ double clamped=qBound(0.5,scale,2.0); double zoom=std::log2(clamped); QByteArray z=QByteArray::number(zoom,'f',3); const char*cmd[]={"set","video-zoom",z.constData(),nullptr}; check_mpv_error(mpv_command_async(mpv,0,cmd));}
void MpvWidget::initializeGL(){mpv_opengl_init_params gl{getProc,nullptr}; mpv_render_param ps[]={{MPV_RENDER_PARAM_API_TYPE,const_cast<char*>(MPV_RENDER_API_TYPE_OPENGL)},{MPV_RENDER_PARAM_OPENGL_INIT_PARAMS,&gl},{MPV_RENDER_PARAM_INVALID,nullptr}}; check_mpv_error(mpv_render_context_create(&ctx,mpv,ps)); mpv_render_context_set_update_callback(ctx,render,this);} 
void MpvWidget::paintGL(){if(!ctx)return; if(cur.isEmpty()){auto*f=QOpenGLContext::currentContext()->functions(); f->glClearColor(0.0f,0.0f,0.0f,1.0f); f->glClear(GL_COLOR_BUFFER_BIT); return;} qreal s=devicePixelRatioF(); mpv_opengl_fbo f{int(defaultFramebufferObject()),int(width()*s),int(height()*s),0}; int flip=1; mpv_render_param ps[]={{MPV_RENDER_PARAM_OPENGL_FBO,&f},{MPV_RENDER_PARAM_FLIP_Y,&flip},{MPV_RENDER_PARAM_INVALID,nullptr}}; mpv_render_context_render(ctx,ps);} 
void*MpvWidget::getProc(void*,const char*n){auto*c=QOpenGLContext::currentContext();return c?reinterpret_cast<void*>(c->getProcAddress(QByteArray(n))):nullptr;} void MpvWidget::render(void*o){auto*s=static_cast<MpvWidget*>(o);QMetaObject::invokeMethod(s,[s]{s->update();},Qt::QueuedConnection);} void MpvWidget::wakeup(void*o){auto*s=static_cast<MpvWidget*>(o);QMetaObject::invokeMethod(s,[s]{s->events();},Qt::QueuedConnection);} void MpvWidget::events(){while(mpv){auto*e=mpv_wait_event(mpv,0); if(!e||e->event_id==MPV_EVENT_NONE)break; if(e->event_id==MPV_EVENT_PROPERTY_CHANGE){prop(static_cast<mpv_event_property*>(e->data));} else if(e->event_id==MPV_EVENT_END_FILE){auto*ef=static_cast<mpv_event_end_file*>(e->data); if(!ef||ef->reason==MPV_END_FILE_REASON_EOF||ef->reason==MPV_END_FILE_REASON_STOP){if(onEndFile)onEndFile();}}}} void MpvWidget::prop(mpv_event_property*p){if(!p||!p->data)return; QString n=p->name; if(n=="time-pos"&&p->format==MPV_FORMAT_DOUBLE){if(onPosition)onPosition(*static_cast<double*>(p->data));} else if(n=="duration"&&p->format==MPV_FORMAT_DOUBLE){if(onDuration)onDuration(*static_cast<double*>(p->data));} else if(n=="pause"&&p->format==MPV_FORMAT_FLAG){if(onPause)onPause(*static_cast<int*>(p->data)!=0);} else if(n=="volume"&&p->format==MPV_FORMAT_DOUBLE){if(onVolume)onVolume(*static_cast<double*>(p->data));} else if(n=="mute"&&p->format==MPV_FORMAT_FLAG){if(onMute)onMute(*static_cast<int*>(p->data)!=0);} else if(n=="path"&&p->format==MPV_FORMAT_STRING){char*v=*static_cast<char**>(p->data);cur=QString::fromUtf8(v?v:""); if(onFile)onFile(cur);}}
