#include "MainWindow.h"
#include "mpv/MpvWidget.h"
#include "playlist/PlaylistModel.h"
#include "playlist/PlaylistDelegate.h"
#include "media/MetadataProbeManager.h"
#include "media/ThumbnailManager.h"
#include "ui/TimelineWidget.h"
#include "util/Utils.h"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QPushButton>
#include <QLabel>
#include <QFileDialog>
#include <QSplitter>
#include <QFileInfo>
#include <QMouseEvent>
#include <QKeyEvent>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QDragMoveEvent>
#include <QEvent>
#include <QMimeData>
#include <QUrl>
#include <QListView>
#include <QTabWidget>
#include <QTextEdit>
#include <QAbstractItemView>
#include <QStandardPaths>
#include <QDir>
#include <QDirIterator>
#include <QSet>
#include <QFile>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QCloseEvent>
#include <QTimer>
#include <QMenu>
#include <QClipboard>
#include <QDesktopServices>
#include <QDateTime>
#include <QTextStream>
#include <QApplication>
#include <QFont>
#include <QShortcut>
#include <QKeySequence>

